In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df=pd.read_csv('j:/data_science/csv/data/fruits.csv')
df

color  sphericity  weight   label
0            Orange       0.947     120  Orange
1            Orange       0.917     125  Orange
2            Orange       0.923     110  Orange
3            Orange       0.916     123  Orange
4            Orange       0.943     124  Orange
5            Orange       0.911     130  Orange
6            Orange       0.903     135  Orange
7            Orange       0.918     105  Orange
8            Orange       0.914     132  Orange
9            Orange       0.936     127  Orange
10  Greenish yellow       0.829     133  Orange
11  Greenish yellow       0.875     134  Orange
12  Greenish yellow       0.859     110  Orange
13            Green       0.849     119  Orange
14            Green       0.868     106  Orange
15  Greenish yellow       0.884     113  Orange
16  Greenish yellow       0.872     108  Orange
17  Greenish yellow       0.823     132  Orange
18            Green       0.853     119  Orange
19            Green       0.808     143  Orange
20  Greenish yellow       0.838     101  Orange
21  Greenish yellow       0.824     149  Orange
22            Green       0.894     136  Orange
23            Green       0.809     141  Orange
24  Greenish yellow       0.880     145  Orange
25            Green       0.834     109  Orange
26            Green       0.809     108  Orange
27            Green       0.860     144  Orange
28            Green       0.870     101  Orange
29  Greenish yellow       0.825     124  Orange
30            Green       0.717     154   Apple
31            Green       0.711     170   Apple
32            Green       0.714     164   Apple
33            Green       0.831     152   Apple
34            Green       0.721     172   Apple
35            Green       0.745     181   Apple
36            Green       0.775     173   Apple
37            Green       0.791     167   Apple
38            Green       0.733     184   Apple
39            Green       0.727     160   Apple
40   Reddish yellow       0.778     174   Apple
41   Reddish yellow       0.772     152   Apple
42              Red       0.776     172   Apple
43              Red       0.821     158   Apple
44              Red       0.727     169   Apple
45              Red       0.801     170   Apple
46   Reddish yellow       0.803     164   Apple
47              Red       0.845     154   Apple
48              Red       0.710     149   Apple
49   Reddish yellow       0.812     160   Apple
50              Red       0.784     142   Apple
51              Red       0.748     140   Apple
52              Red       0.723     165   Apple
53   Reddish yellow       0.815     152   Apple
54   Reddish yellow       0.823     167   Apple
55   Reddish yellow       0.745     172   Apple
56   Reddish yellow       0.753     143   Apple
57   Reddish yellow       0.753     177   Apple
58              Red       0.839     162   Apple
59   Reddish yellow       0.751     140   Apple

In [5]:
from sklearn.model_selection import train_test_split

In [17]:
X=df.iloc[:,[1,2]]
y=df.label
X_train,X_test,y_train, y_test=train_test_split(X,y)

In [19]:
X_test

sphericity  weight
40       0.778     174
41       0.772     152
38       0.733     184
33       0.831     152
39       0.727     160
5        0.911     130
50       0.784     142
37       0.791     167
32       0.714     164
1        0.917     125
6        0.903     135
54       0.823     167
15       0.884     113
58       0.839     162
18       0.853     119

In [21]:
X_train,X_test,y_train, y_test=train_test_split(X,y)
X_test

sphericity  weight
16       0.872     108
11       0.875     134
4        0.943     124
21       0.824     149
39       0.727     160
51       0.748     140
40       0.778     174
9        0.936     127
46       0.803     164
45       0.801     170
34       0.721     172
30       0.717     154
58       0.839     162
42       0.776     172
26       0.809     108

In [23]:
X_train,X_test,y_train, y_test=train_test_split(X,y)
X_test

sphericity  weight
14       0.868     106
52       0.723     165
54       0.823     167
39       0.727     160
53       0.815     152
24       0.880     145
51       0.748     140
56       0.753     143
36       0.775     173
27       0.860     144
23       0.809     141
15       0.884     113
35       0.745     181
12       0.859     110
57       0.753     177

In [25]:
from sklearn.model_selection import KFold

In [57]:
kf=KFold(n_splits=5,shuffle=
         False)

In [59]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [63]:
for i,j in kf.split(X):
    print(f'training ={i }   test={j} ')
    X_train,y_train=X.iloc[i],y.iloc[i]
    X_test,y_test=X.iloc[j],y.iloc[j]
    
    print('-------------X_test=',X_test)
    print('=====')

training =[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]   test=[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-------------X_test=     sphericity  weight
0        0.947     120
1        0.917     125
2        0.923     110
3        0.916     123
4        0.943     124
5        0.911     130
6        0.903     135
7        0.918     105
8        0.914     132
9        0.936     127
10       0.829     133
11       0.875     134
=====
training =[ 0  1  2  3  4  5  6  7  8  9 10 11 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]   test=[12 13 14 15 16 17 18 19 20 21 22 23] 
-------------X_test=     sphericity  weight
12       0.859     110
13       0.849     119
14       0.868     106
15       0.884     113
16       0.872     108
17       0.823     132
18       0.853     119
19       0.808     143
20       0.838     101
21       0.824   

In [35]:
df.shape

(60, 4)

In [69]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy')
sc=[]
for i,j in kf.split(X):
    print(f'training ={i }   test={j} ')
    X_train,y_train=X.iloc[i],y.iloc[i]
    X_test,y_test=X.iloc[j],y.iloc[j]
    model.fit(X_train,y_train)
    sc.append(model.score(X_test,y_test))
    
    print('-------------X_test=',X_test)
    print('=====')

print(sc)

training =[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]   test=[ 0  1  2  3  4  5  6  7  8  9 10 11] 
-------------X_test=     sphericity  weight
0        0.947     120
1        0.917     125
2        0.923     110
3        0.916     123
4        0.943     124
5        0.911     130
6        0.903     135
7        0.918     105
8        0.914     132
9        0.936     127
10       0.829     133
11       0.875     134
=====
training =[ 0  1  2  3  4  5  6  7  8  9 10 11 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]   test=[12 13 14 15 16 17 18 19 20 21 22 23] 
-------------X_test=     sphericity  weight
12       0.859     110
13       0.849     119
14       0.868     106
15       0.884     113
16       0.872     108
17       0.823     132
18       0.853     119
19       0.808     143
20       0.838     101
21       0.824   

In [71]:
np.mean(sc)

0.8666666666666666

In [75]:
from sklearn.model_selection import cross_val_score,cross_validate

In [91]:
df.label=df.label.replace({'Apple':0,'Orange':1})
df

C:\Users\Malay\AppData\Local\Temp\ipykernel_13596\1445231481.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.label=df.label.replace({'Apple':0,'Orange':1})


color  sphericity  weight  label
0            Orange       0.947     120      1
1            Orange       0.917     125      1
2            Orange       0.923     110      1
3            Orange       0.916     123      1
4            Orange       0.943     124      1
5            Orange       0.911     130      1
6            Orange       0.903     135      1
7            Orange       0.918     105      1
8            Orange       0.914     132      1
9            Orange       0.936     127      1
10  Greenish yellow       0.829     133      1
11  Greenish yellow       0.875     134      1
12  Greenish yellow       0.859     110      1
13            Green       0.849     119      1
14            Green       0.868     106      1
15  Greenish yellow       0.884     113      1
16  Greenish yellow       0.872     108      1
17  Greenish yellow       0.823     132      1
18            Green       0.853     119      1
19            Green       0.808     143      1
20  Greenish yellow       0.838     101      1
21  Greenish yellow       0.824     149      1
22            Green       0.894     136      1
23            Green       0.809     141      1
24  Greenish yellow       0.880     145      1
25            Green       0.834     109      1
26            Green       0.809     108      1
27            Green       0.860     144      1
28            Green       0.870     101      1
29  Greenish yellow       0.825     124      1
30            Green       0.717     154      0
31            Green       0.711     170      0
32            Green       0.714     164      0
33            Green       0.831     152      0
34            Green       0.721     172      0
35            Green       0.745     181      0
36            Green       0.775     173      0
37            Green       0.791     167      0
38            Green       0.733     184      0
39            Green       0.727     160      0
40   Reddish yellow       0.778     174      0
41   Reddish yellow       0.772     152      0
42              Red       0.776     172      0
43              Red       0.821     158      0
44              Red       0.727     169      0
45              Red       0.801     170      0
46   Reddish yellow       0.803     164      0
47              Red       0.845     154      0
48              Red       0.710     149      0
49   Reddish yellow       0.812     160      0
50              Red       0.784     142      0
51              Red       0.748     140      0
52              Red       0.723     165      0
53   Reddish yellow       0.815     152      0
54   Reddish yellow       0.823     167      0
55   Reddish yellow       0.745     172      0
56   Reddish yellow       0.753     143      0
57   Reddish yellow       0.753     177      0
58              Red       0.839     162      0
59   Reddish yellow       0.751     140      0

In [93]:
X=df.iloc[:,[1,2]]
y=df.label

In [95]:
cross_val_score(model,X,y,scoring='recall')

array([1. , 1. , 1. , 0.5, 1. ])

In [97]:
cross_val_score(model,X,y,scoring='f1')

array([1.        , 1.        , 1.        , 0.66666667, 1.        ])

In [99]:
cross_val_score(model,X,y,scoring='precision')

array([1., 1., 1., 1., 1.])

In [101]:
cross_val_score(model,X,y,scoring='balanced_accuracy')

array([1.  , 1.  , 1.  , 0.75, 1.  ])

In [103]:
cross_validate(model,X,y,scoring=['accuracy','recall','f1','balanced_accuracy'])

{'fit_time': array([0.00500798, 0.00351501, 0.0030036 , 0.00100374, 0.00150967]),
 'score_time': array([0.02763033, 0.01359868, 0.00450516, 0.00400329, 0.0035336 ]),
 'test_accuracy': array([1.  , 1.  , 1.  , 0.75, 1.  ]),
 'test_recall': array([1. , 1. , 1. , 0.5, 1. ]),
 'test_f1': array([1.        , 1.        , 1.        , 0.66666667, 1.        ]),
 'test_balanced_accuracy': array([1.  , 1.  , 1.  , 0.75, 1.  ])}

In [107]:
# manually grid search CV  KNN

In [109]:
from sklearn.neighbors import KNeighborsClassifier

In [125]:
max_sc=0
for i in [3,5,7]:
    for j in [1,2]:
        for k in ['uniform','distance']:
                model=KNeighborsClassifier(n_neighbors=i,p=j,weights=k)
                model.fit(X_train,y_train)
                sc=model.score(X_test,y_test)
                print(f'n_neighbors : {i}  p={j}  weights={k}  sc={sc}')
                if sc>max_sc:
                    max_sc=sc
                    
                    best_comb={'n_neighbors':i,'p':j,'weight':k}


print('=================')
best_comb
                    

n_neighbors : 3  p=1  weights=uniform  sc=0.6666666666666666
n_neighbors : 3  p=1  weights=distance  sc=0.5833333333333334
n_neighbors : 3  p=2  weights=uniform  sc=0.6666666666666666
n_neighbors : 3  p=2  weights=distance  sc=0.5833333333333334
n_neighbors : 5  p=1  weights=uniform  sc=0.6666666666666666
n_neighbors : 5  p=1  weights=distance  sc=0.5833333333333334
n_neighbors : 5  p=2  weights=uniform  sc=0.6666666666666666
n_neighbors : 5  p=2  weights=distance  sc=0.5833333333333334
n_neighbors : 7  p=1  weights=uniform  sc=0.6666666666666666
n_neighbors : 7  p=1  weights=distance  sc=0.5833333333333334
n_neighbors : 7  p=2  weights=uniform  sc=0.6666666666666666
n_neighbors : 7  p=2  weights=distance  sc=0.5833333333333334


{'n_neighbors': 3, 'p': 1, 'weight': 'uniform'}

In [115]:
from sklearn.model_selection import GridSearchCV

In [119]:
model=KNeighborsClassifier()
param={'n_neighbors':[3,5,7],'p':[1,2],'weights':['uniform','distance']}
gs=GridSearchCV(model,param_grid=param)
gs.fit(X,y)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']})

In [121]:
gs.best_estimator_

KNeighborsClassifier(n_neighbors=3, p=1)

In [123]:
gs.best_params_

{'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}

In [127]:
gs.cv_results_

{'mean_fit_time': array([0.00435319, 0.00200653, 0.00131621, 0.00099835, 0.00130591,
        0.00254703, 0.00150709, 0.00079799, 0.00071087, 0.00110922,
        0.00100131, 0.00206151]),
 'std_fit_time': array([2.34976812e-03, 1.31362114e-03, 6.22940045e-04, 6.31958739e-04,
        9.80072651e-04, 1.66844473e-03, 4.54513800e-04, 7.46290462e-04,
        9.98638702e-04, 2.04666629e-04, 1.45728176e-06, 9.31356460e-04]),
 'mean_score_time': array([0.00516696, 0.00140948, 0.00200853, 0.00161366, 0.00160823,
        0.00231986, 0.00220919, 0.00090504, 0.00170069, 0.0008028 ,
        0.00241647, 0.00150266]),
 'std_score_time': array([0.00545781, 0.00037687, 0.00084673, 0.00097386, 0.00058506,
        0.00098764, 0.00051137, 0.00019304, 0.00039904, 0.00040147,
        0.00087329, 0.00044824]),
 'param_n_neighbors': masked_array(data=[3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],

In [129]:
pd.DataFrame(gs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.004353      0.002350         0.005167        0.005458   
1        0.002007      0.001314         0.001409        0.000377   
2        0.001316      0.000623         0.002009        0.000847   
3        0.000998      0.000632         0.001614        0.000974   
4        0.001306      0.000980         0.001608        0.000585   
5        0.002547      0.001668         0.002320        0.000988   
6        0.001507      0.000455         0.002209        0.000511   
7        0.000798      0.000746         0.000905        0.000193   
8        0.000711      0.000999         0.001701        0.000399   
9        0.001109      0.000205         0.000803        0.000401   
10       0.001001      0.000001         0.002416        0.000873   
11       0.002062      0.000931         0.001503        0.000448   

    param_n_neighbors  param_p param_weights  \
0                   3        1       uniform   
1                   3        1      distance   
2                   3        2       uniform   
3                   3        2      distance   
4                   5        1       uniform   
5                   5        1      distance   
6                   5        2       uniform   
7                   5        2      distance   
8                   7        1       uniform   
9                   7        1      distance   
10                  7        2       uniform   
11                  7        2      distance   

                                               params  split0_test_score  \
0    {'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}                1.0   
1   {'n_neighbors': 3, 'p': 1, 'weights': 'distance'}                1.0   
2    {'n_neighbors': 3, 'p': 2, 'weights': 'uniform'}                1.0   
3   {'n_neighbors': 3, 'p': 2, 'weights': 'distance'}                1.0   
4    {'n_neighbors': 5, 'p': 1, 'weights': 'uniform'}                1.0   
5   {'n_neighbors': 5, 'p': 1, 'weights': 'distance'}                1.0   
6    {'n_neighbors': 5, 'p': 2, 'weights': 'uniform'}                1.0   
7   {'n_neighbors': 5, 'p': 2, 'weights': 'distance'}                1.0   
8    {'n_neighbors': 7, 'p': 1, 'weights': 'uniform'}                1.0   
9   {'n_neighbors': 7, 'p': 1, 'weights': 'distance'}                1.0   
10   {'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}                1.0   
11  {'n_neighbors': 7, 'p': 2, 'weights': 'distance'}                1.0   

    split1_test_score  split2_test_score  split3_test_score  \
0                 1.0                1.0           0.833333   
1                 1.0                1.0           0.750000   
2                 1.0                1.0           0.833333   
3                 1.0                1.0           0.750000   
4                 1.0                1.0           0.750000   
5                 1.0                1.0           0.750000   
6                 1.0                1.0           0.750000   
7                 1.0                1.0           0.750000   
8                 1.0                1.0           0.666667   
9                 1.0                1.0           0.750000   
10                1.0                1.0           0.666667   
11                1.0                1.0           0.750000   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.916667         0.950000        0.066667                1  
1            0.916667         0.933333        0.097183                3  
2            0.916667         0.950000        0.066667                1  
3            0.916667         0.933333        0.097183                3  
4            0.916667         0.933333        0.097183                3  
5            0.916667         0.933333        0.097183                3  
6            0.916667         0.933333        0.097183                3  
7            0.916667         0.933333        0.097183                3  
8            0.6666