In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df=pd.read_csv('j:/data_science/csv/classification/Cancer_data_1500_V2.csv')
df

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0      58       1  16.085313        0            1          8.146251   
1      71       0  30.828784        0            1          9.361630   
2      48       1  38.785084        0            2          5.135179   
3      34       0  30.040296        0            0          9.502792   
4      62       1  35.479721        0            0          5.356890   
...   ...     ...        ...      ...          ...               ...   
1495   62       1  25.090025        0            0          9.892167   
1496   31       0  33.447125        0            1          1.668297   
1497   63       1  32.613861        1            1          0.466848   
1498   55       0  25.568216        0            0          7.795317   
1499   67       1  23.663104        0            0          2.525860   

      AlcoholIntake  CancerHistory  Diagnosis  
0          4.148219              1          1  
1          3.519683              0          0  
2          4.728368              0          1  
3          2.044636              0          0  
4          3.309849              0          1  
...             ...            ...        ...  
1495       1.284158              0          1  
1496       2.280636              1          1  
1497       0.150101              0          1  
1498       1.986138              1          1  
1499       2.856600              1          0  

[1500 rows x 9 columns]

In [5]:
#bootrapping

In [13]:
df1=df.sample(500,replace=True,axis=0)
df2=df.sample(500,replace=True,axis=0)
df3=df.sample(500,replace=True,axis=0)

In [11]:
df.sample(500,replace=False,axis=0)

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
371    43       1  25.315546        0            0          5.051156   
971    30       1  33.067674        0            1          7.476518   
609    35       0  23.698535        0            1          3.205676   
11     42       0  37.500578        1            2          8.319415   
1153   49       1  39.400346        0            0          1.355169   
...   ...     ...        ...      ...          ...               ...   
1120   80       1  33.464936        0            0          2.624161   
654    35       0  25.563711        0            1          3.789559   
134    30       1  31.024302        0            2          1.163317   
206    70       0  39.396844        0            1          4.003299   
1357   20       1  16.365861        0            1          2.168143   

      AlcoholIntake  CancerHistory  Diagnosis  
371        2.054803              0          0  
971        4.230969              0          0  
609        1.924794              0          0  
11         4.053019              0          1  
1153       4.141891              0          1  
...             ...            ...        ...  
1120       1.261116              0          0  
654        4.684746              0          0  
134        3.074515              0          1  
206        1.236030              0          0  
1357       3.133919              0          0  

[500 rows x 9 columns]

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
dt1=DecisionTreeClassifier(criterion='entropy')
dt2=DecisionTreeClassifier(criterion='entropy')
dt3=DecisionTreeClassifier(criterion='entropy')


In [19]:
X=df1.iloc[:,:-1]
y=df1.iloc[:,-1]
dt1.fit(X,y)

DecisionTreeClassifier(criterion='entropy')

In [21]:
X=df2.iloc[:,:-1]
y=df2.iloc[:,-1]
dt2.fit(X,y)

DecisionTreeClassifier(criterion='entropy')

In [23]:
X=df3.iloc[:,:-1]
y=df3.iloc[:,-1]
dt3.fit(X,y)

DecisionTreeClassifier(criterion='entropy')

In [25]:
#testing

In [27]:
df3

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
899    50       1  19.865596        0            1          2.286708   
257    77       0  34.366338        0            0          4.431273   
1432   46       0  25.941533        0            1          3.429665   
1260   74       1  26.922503        1            1          7.892907   
581    42       1  25.687242        0            1          6.995279   
...   ...     ...        ...      ...          ...               ...   
119    79       1  38.264880        0            1          9.865695   
931    60       0  34.855267        0            0          0.388129   
736    31       1  18.500602        1            0          7.292402   
347    71       1  33.326782        1            0          2.778911   
592    73       1  35.476588        0            0          7.563561   

      AlcoholIntake  CancerHistory  Diagnosis  
899        4.293360              0          0  
257        0.534956              0          0  
1432       3.774363              0          0  
1260       0.202546              1          1  
581        1.168045              0          0  
...             ...            ...        ...  
119        3.464006              0          1  
931        4.781106              0          1  
736        2.938977              0          0  
347        4.243838              0          1  
592        0.601355              0          0  

[500 rows x 9 columns]

In [29]:
q=[[50	,1	,19.865596	,0	,1,	2.286708	,4.293360,	0]]
q

[[50, 1, 19.865596, 0, 1, 2.286708, 4.29336, 0]]

In [31]:
dt1.predict(q),dt2.predict(q),dt3.predict(q)

F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(array([1], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))

In [33]:
q=[[73,	1,	35.476588	,0,	0	,7.563561,	0.601355,	0]]
q

[[73, 1, 35.476588, 0, 0, 7.563561, 0.601355, 0]]

In [35]:
dt1.predict(q),dt2.predict(q),dt3.predict(q)

F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


(array([0], dtype=int64), array([0], dtype=int64), array([0], dtype=int64))

In [37]:
#using random forest

In [41]:
from sklearn.ensemble import RandomForestClassifier,BaggingClassifier,VotingClassifier,AdaBoostClassifier

In [43]:
rf=RandomForestClassifier(n_estimators=3,criterion='entropy')
rf

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [45]:
X

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
899    50       1  19.865596        0            1          2.286708   
257    77       0  34.366338        0            0          4.431273   
1432   46       0  25.941533        0            1          3.429665   
1260   74       1  26.922503        1            1          7.892907   
581    42       1  25.687242        0            1          6.995279   
...   ...     ...        ...      ...          ...               ...   
119    79       1  38.264880        0            1          9.865695   
931    60       0  34.855267        0            0          0.388129   
736    31       1  18.500602        1            0          7.292402   
347    71       1  33.326782        1            0          2.778911   
592    73       1  35.476588        0            0          7.563561   

      AlcoholIntake  CancerHistory  
899        4.293360              0  
257        0.534956              0  
1432       3.774363              0  
1260       0.202546              1  
581        1.168045              0  
...             ...            ...  
119        3.464006              0  
931        4.781106              0  
736        2.938977              0  
347        4.243838              0  
592        0.601355              0  

[500 rows x 8 columns]

In [47]:
X=df1.iloc[:,:-1]
y=df1.iloc[:,-1]


In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y)
rf.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [51]:
rf.score(X_test,y_test)

0.784

In [55]:
rf.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1988008984),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=626020426),
 DecisionTreeClassifier(criterion='entropy', max_features='sqrt',
                        random_state=1241918009)]

In [57]:
pred={
    'actual':y_test
}

In [59]:
for i in rf.estimators_:
    pred[i]=i.predict(X_test)
pd.DataFrame(pred)

F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


actual  \
1131       0   
1397       0   
606        0   
183        0   
1084       0   
...      ...   
395        1   
1070       0   
1081       0   
405        0   
468        0   

      DecisionTreeClassifier(criterion='entropy', max_features='sqrt',\n                       random_state=1988008984)  \
1131                                                0.0                                                                   
1397                                                0.0                                                                   
606                                                 0.0                                                                   
183                                                 1.0                                                                   
1084                                                0.0                                                                   
...                                                 ...                                                                   
395                                                 1.0                                                                   
1070                                                0.0                                                                   
1081                                                0.0                                                                   
405                                                 0.0                                                                   
468                                                 0.0                                                                   

      DecisionTreeClassifier(criterion='entropy', max_features='sqrt',\n                       random_state=626020426)  \
1131                                                0.0                                                                  
1397                                                0.0                                                                  
606                                                 0.0                                                                  
183                                                 0.0                                                                  
1084                                                0.0                                                                  
...                                                 ...                                                                  
395                                                 1.0                                                                  
1070                                                0.0                                                                  
1081                                                0.0                                                                  
405                                                 0.0                                                                  
468                                                 0.0                                                                  

      DecisionTreeClassifier(criterion='entropy', max_features='sqrt',\n                       random_state=1241918009)  
1131                                                0.0                                                                  
1397                                                0.0                                                                  
606                                                 0.0                                                                  
183                                                 0.0                                                                  
1084                                                0.0                                                                  
...                                                 ...                                                                  
395              

In [61]:
from sklearn.neighbors import KNeighborsClassifier
bc=BaggingClassifier(estimator=KNeighborsClassifier(),n_estimators=3)
bc

BaggingClassifier(estimator=KNeighborsClassifier(), n_estimators=3)

In [63]:
bc.fit(X_train,y_train)

BaggingClassifier(estimator=KNeighborsClassifier(), n_estimators=3)

In [65]:
bc.estimators_

[KNeighborsClassifier(), KNeighborsClassifier(), KNeighborsClassifier()]

In [67]:
pred={
    'actual':y_test
}

for i in bc.estimators_:
    pred[i]=i.predict(X_test)
pd.DataFrame(pred)


F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
F:\anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


actual  KNeighborsClassifier()  KNeighborsClassifier()  \
1131       0                       0                       0   
1397       0                       0                       0   
606        0                       0                       0   
183        0                       0                       1   
1084       0                       1                       0   
...      ...                     ...                     ...   
395        1                       1                       1   
1070       0                       1                       0   
1081       0                       0                       0   
405        0                       0                       0   
468        0                       0                       1   

      KNeighborsClassifier()  
1131                       0  
1397                       0  
606                        0  
183                        1  
1084                       1  
...                      ...  
395                        1  
1070                       1  
1081                       0  
405                        0  
468                        0  

[125 rows x 4 columns]

In [69]:
bc.score(X_test,y_test)

0.656

In [71]:
#voting classifier

In [73]:
from sklearn.linear_model import LogisticRegression

In [75]:

est=[

    ('lr',LogisticRegression()),
    ('knn',KNeighborsClassifier()),
    ('dt',DecisionTreeClassifier(criterion='entropy'))


]

In [77]:
from sklearn.model_selection import cross_val_score

In [79]:
for  i in est:
   print( cross_val_score(i[1],X,y)  )
    

[0.85 0.86 0.85 0.89 0.86]
[0.71 0.63 0.62 0.69 0.74]
[0.87 0.86 0.87 0.81 0.93]


F:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
F:\anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [81]:
df

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0      58       1  16.085313        0            1          8.146251   
1      71       0  30.828784        0            1          9.361630   
2      48       1  38.785084        0            2          5.135179   
3      34       0  30.040296        0            0          9.502792   
4      62       1  35.479721        0            0          5.356890   
...   ...     ...        ...      ...          ...               ...   
1495   62       1  25.090025        0            0          9.892167   
1496   31       0  33.447125        0            1          1.668297   
1497   63       1  32.613861        1            1          0.466848   
1498   55       0  25.568216        0            0          7.795317   
1499   67       1  23.663104        0            0          2.525860   

      AlcoholIntake  CancerHistory  Diagnosis  
0          4.148219              1          1  
1          3.519683              0          0  
2          4.728368              0          1  
3          2.044636              0          0  
4          3.309849              0          1  
...             ...            ...        ...  
1495       1.284158              0          1  
1496       2.280636              1          1  
1497       0.150101              0          1  
1498       1.986138              1          1  
1499       2.856600              1          0  

[1500 rows x 9 columns]

In [83]:
df.select_dtypes(float)

BMI  PhysicalActivity  AlcoholIntake
0     16.085313          8.146251       4.148219
1     30.828784          9.361630       3.519683
2     38.785084          5.135179       4.728368
3     30.040296          9.502792       2.044636
4     35.479721          5.356890       3.309849
...         ...               ...            ...
1495  25.090025          9.892167       1.284158
1496  33.447125          1.668297       2.280636
1497  32.613861          0.466848       0.150101
1498  25.568216          7.795317       1.986138
1499  23.663104          2.525860       2.856600

[1500 rows x 3 columns]

In [85]:
from sklearn.preprocessing import StandardScaler

In [87]:
sc=StandardScaler()
sc

StandardScaler()

In [89]:
sc.fit_transform(df.select_dtypes(float))

array([[-1.58116185,  1.1337129 ,  1.21946526],
       [ 0.45872244,  1.55789869,  0.77647404],
       [ 1.55954393,  0.08280367,  1.62835335],
       ...,
       [ 0.70570289, -1.54651364, -1.59840354],
       [-0.26912183,  1.01123176, -0.30436716],
       [-0.5327102 , -0.82788764,  0.30913374]])

In [91]:
df2=df.copy()
df2

Age  Gender        BMI  Smoking  GeneticRisk  PhysicalActivity  \
0      58       1  16.085313        0            1          8.146251   
1      71       0  30.828784        0            1          9.361630   
2      48       1  38.785084        0            2          5.135179   
3      34       0  30.040296        0            0          9.502792   
4      62       1  35.479721        0            0          5.356890   
...   ...     ...        ...      ...          ...               ...   
1495   62       1  25.090025        0            0          9.892167   
1496   31       0  33.447125        0            1          1.668297   
1497   63       1  32.613861        1            1          0.466848   
1498   55       0  25.568216        0            0          7.795317   
1499   67       1  23.663104        0            0          2.525860   

      AlcoholIntake  CancerHistory  Diagnosis  
0          4.148219              1          1  
1          3.519683              0          0  
2          4.728368              0          1  
3          2.044636              0          0  
4          3.309849              0          1  
...             ...            ...        ...  
1495       1.284158              0          1  
1496       2.280636              1          1  
1497       0.150101              0          1  
1498       1.986138              1          1  
1499       2.856600              1          0  

[1500 rows x 9 columns]

In [105]:
df3=pd.concat(   (df[['Age']],df.select_dtypes(float)),axis=1)
df3
df2[['Age','BMI'		,	'PhysicalActivity',	'AlcoholIntake']]=sc.fit_transform(df3)
df2


Age  Gender       BMI  Smoking  GeneticRisk  PhysicalActivity  \
0     0.435495       1 -1.581162        0            1          1.133713   
1     1.172662       0  0.458722        0            1          1.557899   
2    -0.131556       1  1.559544        0            2          0.082804   
3    -0.925428       0  0.349628        0            0          1.607166   
4     0.662316       1  1.102219        0            0          0.160184   
...        ...     ...       ...      ...          ...               ...   
1495  0.662316       1 -0.335284        0            0          1.743064   
1496 -1.095543       0  0.820992        0            1         -1.127190   
1497  0.719021       1  0.705703        1            1         -1.546514   
1498  0.265380       0 -0.269122        0            0          1.011232   
1499  0.945842       1 -0.532710        0            0         -0.827888   

      AlcoholIntake  CancerHistory  Diagnosis  
0          1.219465              1          1  
1          0.776474              0          0  
2          1.628353              0          1  
3         -0.263137              0          0  
4          0.628583              0          1  
...             ...            ...        ...  
1495      -0.799122              0          1  
1496      -0.096805              1          1  
1497      -1.598404              0          1  
1498      -0.304367              1          1  
1499       0.309134              1          0  

[1500 rows x 9 columns]

In [107]:
X=df2.iloc[:,:-1]
y=df2.iloc[:,-1]
for  i in est:
   print( cross_val_score(i[1],X,y)  )

[0.88       0.85       0.88       0.86333333 0.77333333]
[0.85333333 0.84333333 0.84333333 0.87333333 0.75666667]
[0.90666667 0.86666667 0.92       0.89       0.79      ]


In [109]:
df2

Age  Gender       BMI  Smoking  GeneticRisk  PhysicalActivity  \
0     0.435495       1 -1.581162        0            1          1.133713   
1     1.172662       0  0.458722        0            1          1.557899   
2    -0.131556       1  1.559544        0            2          0.082804   
3    -0.925428       0  0.349628        0            0          1.607166   
4     0.662316       1  1.102219        0            0          0.160184   
...        ...     ...       ...      ...          ...               ...   
1495  0.662316       1 -0.335284        0            0          1.743064   
1496 -1.095543       0  0.820992        0            1         -1.127190   
1497  0.719021       1  0.705703        1            1         -1.546514   
1498  0.265380       0 -0.269122        0            0          1.011232   
1499  0.945842       1 -0.532710        0            0         -0.827888   

      AlcoholIntake  CancerHistory  Diagnosis  
0          1.219465              1          1  
1          0.776474              0          0  
2          1.628353              0          1  
3         -0.263137              0          0  
4          0.628583              0          1  
...             ...            ...        ...  
1495      -0.799122              0          1  
1496      -0.096805              1          1  
1497      -1.598404              0          1  
1498      -0.304367              1          1  
1499       0.309134              1          0  

[1500 rows x 9 columns]

In [111]:
vt1=VotingClassifier(estimators=est)
vt1


VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('dt',
                              DecisionTreeClassifier(criterion='entropy'))])

In [113]:

X=df2.iloc[:,:-1]
y=df2.iloc[:,-1]
X_train,X_test,y_train,y_test=train_test_split(X,y)
vt1.fit(X_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('dt',
                              DecisionTreeClassifier(criterion='entropy'))])

In [115]:
for  i in vt1.estimators_:
   print( cross_val_score(i,X,y)  )

[0.88       0.85       0.88       0.86333333 0.77333333]
[0.85333333 0.84333333 0.84333333 0.87333333 0.75666667]
[0.91666667 0.87666667 0.92       0.89       0.79333333]


In [117]:
# [0.88       0.85       0.88       0.86333333 0.77333333]
# [0.85333333 0.84333333 0.84333333 0.87333333 0.75666667]
# [0.90666667 0.86666667 0.92       0.89       0.79      ]


In [119]:
vt2=VotingClassifier(estimators=est,voting='soft')
vt2


VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('dt',
                              DecisionTreeClassifier(criterion='entropy'))],
                 voting='soft')

In [121]:
vt2.fit(X_train,y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('dt',
                              DecisionTreeClassifier(criterion='entropy'))],
                 voting='soft')

In [123]:
for  i in vt2.estimators_:
   print( cross_val_score(i,X,y)  )

[0.88       0.85       0.88       0.86333333 0.77333333]
[0.85333333 0.84333333 0.84333333 0.87333333 0.75666667]
[0.90666667 0.88       0.91666667 0.89333333 0.78666667]


In [125]:
# [0.88       0.85       0.88       0.86333333 0.77333333]
# [0.85333333 0.84333333 0.84333333 0.87333333 0.75666667]
# [0.90666667 0.86666667 0.92       0.89       0.79      ]

In [127]:
#staking 

In [129]:
from sklearn.ensemble import StackingClassifier

In [131]:
stc=StackingClassifier(estimators=est)
stc

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('knn', KNeighborsClassifier()),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy'))])

In [133]:
stc.fit(X_train,y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('knn', KNeighborsClassifier()),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy'))])

In [135]:
pred={
    
}

In [139]:
for  i in stc.estimators_:
    pred[i]=i.predict(X_test)

d1=pd.DataFrame(pred)
d1

LogisticRegression()  KNeighborsClassifier()  \
0                       0                       0   
1                       1                       1   
2                       0                       0   
3                       1                       1   
4                       0                       0   
..                    ...                     ...   
370                     1                       1   
371                     0                       0   
372                     1                       1   
373                     1                       1   
374                     1                       0   

     DecisionTreeClassifier(criterion='entropy')  
0                                              0  
1                                              1  
2                                              0  
3                                              0  
4                                              0  
..                                           ...  
370                                            1  
371                                            0  
372                                            1  
373                                            1  
374                                            0  

[375 rows x 3 columns]

In [141]:
stc.final_estimator_.fit(d1,y_test)

LogisticRegression()

In [149]:
pred={
    'actual':y_test,
    'pred':stc.final_estimator_.predict(d1)
}
pd.DataFrame(pred)

actual  pred
1225       0     0
141        1     1
1283       0     0
901        1     1
204        0     0
...      ...   ...
735        1     1
521        0     0
838        1     1
1200       1     1
899        0     0

[375 rows x 2 columns]