In [1]:
import numpy as np

In [3]:
x=np.random.randint(10,20,size=(5,8))
x

array([[11, 13, 17, 14, 19, 18, 12, 12],
       [13, 19, 14, 17, 13, 15, 19, 19],
       [15, 11, 10, 16, 19, 15, 10, 17],
       [13, 13, 16, 10, 17, 15, 18, 11],
       [11, 15, 15, 13, 12, 15, 15, 16]])

In [7]:
x[  np.ix_([2,3],[4,5,6] )    ]

array([[19, 15, 10],
       [17, 15, 18]])

In [9]:
#sorting 1D array

In [11]:
x=np.random.randint(10,20,size=(10))
x

array([17, 15, 19, 17, 15, 15, 11, 15, 15, 16])

In [13]:
np.sort(x)

array([11, 15, 15, 15, 15, 15, 16, 17, 17, 19])

In [15]:
x

array([17, 15, 19, 17, 15, 15, 11, 15, 15, 16])

In [17]:
x=np.random.randint(10,20,size=(4,5))
x

array([[10, 10, 17, 15, 14],
       [14, 16, 10, 18, 12],
       [14, 13, 12, 15, 16],
       [15, 13, 16, 18, 12]])

In [19]:
np.sort(x)

array([[10, 10, 14, 15, 17],
       [10, 12, 14, 16, 18],
       [12, 13, 14, 15, 16],
       [12, 13, 15, 16, 18]])

In [21]:
np.sort(x,axis=0)

array([[10, 10, 10, 15, 12],
       [14, 13, 12, 15, 12],
       [14, 13, 16, 18, 14],
       [15, 16, 17, 18, 16]])

In [23]:
np.sort(x,axis=None)

array([10, 10, 10, 12, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
       17, 18, 18])

In [25]:
x=np.random.randint(10,20,size=(10))
y=np.random.randint(100,200,size=(10))

In [27]:
x,y

(array([14, 18, 18, 16, 15, 10, 10, 12, 15, 10]),
 array([153, 185, 115, 109, 100, 106, 132, 188, 114, 153]))

In [29]:
np.stack((x,y))

array([[ 14,  18,  18,  16,  15,  10,  10,  12,  15,  10],
       [153, 185, 115, 109, 100, 106, 132, 188, 114, 153]])

In [31]:
np.stack((x,y),axis=1)

array([[ 14, 153],
       [ 18, 185],
       [ 18, 115],
       [ 16, 109],
       [ 15, 100],
       [ 10, 106],
       [ 10, 132],
       [ 12, 188],
       [ 15, 114],
       [ 10, 153]])

In [33]:
x=np.random.randint(10,20,size=(4,5))
y=np.random.randint(100,200,size=(4,5))
x,y

(array([[10, 19, 19, 15, 10],
        [16, 17, 12, 15, 12],
        [19, 14, 16, 19, 13],
        [15, 19, 12, 17, 10]]),
 array([[172, 101, 139, 101, 155],
        [128, 100, 159, 149, 156],
        [130, 134, 132, 199, 118],
        [176, 148, 139, 131, 135]]))

In [35]:
np.stack((x,y))

array([[[ 10,  19,  19,  15,  10],
        [ 16,  17,  12,  15,  12],
        [ 19,  14,  16,  19,  13],
        [ 15,  19,  12,  17,  10]],

       [[172, 101, 139, 101, 155],
        [128, 100, 159, 149, 156],
        [130, 134, 132, 199, 118],
        [176, 148, 139, 131, 135]]])

In [37]:
np.stack((x,y),axis=1)

array([[[ 10,  19,  19,  15,  10],
        [172, 101, 139, 101, 155]],

       [[ 16,  17,  12,  15,  12],
        [128, 100, 159, 149, 156]],

       [[ 19,  14,  16,  19,  13],
        [130, 134, 132, 199, 118]],

       [[ 15,  19,  12,  17,  10],
        [176, 148, 139, 131, 135]]])

In [39]:
x=np.random.randint(10,20,size=(4,5))
y=np.random.randint(100,200,size=(4,5))
x,y

(array([[12, 13, 18, 10, 18],
        [17, 12, 16, 16, 19],
        [15, 12, 17, 14, 17],
        [13, 14, 13, 14, 15]]),
 array([[182, 113, 101, 132, 131],
        [128, 161, 145, 101, 112],
        [114, 124, 180, 155, 154],
        [124, 100, 184, 120, 119]]))

In [41]:
np.hstack((x,y))

array([[ 12,  13,  18,  10,  18, 182, 113, 101, 132, 131],
       [ 17,  12,  16,  16,  19, 128, 161, 145, 101, 112],
       [ 15,  12,  17,  14,  17, 114, 124, 180, 155, 154],
       [ 13,  14,  13,  14,  15, 124, 100, 184, 120, 119]])

In [43]:
np.vstack((x,y))

array([[ 12,  13,  18,  10,  18],
       [ 17,  12,  16,  16,  19],
       [ 15,  12,  17,  14,  17],
       [ 13,  14,  13,  14,  15],
       [182, 113, 101, 132, 131],
       [128, 161, 145, 101, 112],
       [114, 124, 180, 155, 154],
       [124, 100, 184, 120, 119]])

In [45]:
np.concatenate((x,y))

array([[ 12,  13,  18,  10,  18],
       [ 17,  12,  16,  16,  19],
       [ 15,  12,  17,  14,  17],
       [ 13,  14,  13,  14,  15],
       [182, 113, 101, 132, 131],
       [128, 161, 145, 101, 112],
       [114, 124, 180, 155, 154],
       [124, 100, 184, 120, 119]])

In [47]:
np.concatenate((x,y),axis=1)

array([[ 12,  13,  18,  10,  18, 182, 113, 101, 132, 131],
       [ 17,  12,  16,  16,  19, 128, 161, 145, 101, 112],
       [ 15,  12,  17,  14,  17, 114, 124, 180, 155, 154],
       [ 13,  14,  13,  14,  15, 124, 100, 184, 120, 119]])

In [49]:
x

array([[12, 13, 18, 10, 18],
       [17, 12, 16, 16, 19],
       [15, 12, 17, 14, 17],
       [13, 14, 13, 14, 15]])

In [51]:
x=np.random.randint(10,20,size=(6,7))
x

array([[12, 10, 12, 17, 15, 10, 10],
       [15, 15, 14, 17, 18, 11, 18],
       [19, 13, 17, 17, 14, 15, 14],
       [12, 12, 17, 14, 10, 12, 14],
       [11, 12, 15, 17, 11, 13, 17],
       [18, 12, 19, 16, 13, 11, 12]])

In [53]:
np.split(x,2)

[array([[12, 10, 12, 17, 15, 10, 10],
        [15, 15, 14, 17, 18, 11, 18],
        [19, 13, 17, 17, 14, 15, 14]]),
 array([[12, 12, 17, 14, 10, 12, 14],
        [11, 12, 15, 17, 11, 13, 17],
        [18, 12, 19, 16, 13, 11, 12]])]

In [63]:
np.split(x,[2, 4],axis=1)
#  0:2   2:4  4:

[array([[12, 10],
        [15, 15],
        [19, 13],
        [12, 12],
        [11, 12],
        [18, 12]]),
 array([[12, 17],
        [14, 17],
        [17, 17],
        [17, 14],
        [15, 17],
        [19, 16]]),
 array([[15, 10, 10],
        [18, 11, 18],
        [14, 15, 14],
        [10, 12, 14],
        [11, 13, 17],
        [13, 11, 12]])]

In [65]:
x

array([[12, 10, 12, 17, 15, 10, 10],
       [15, 15, 14, 17, 18, 11, 18],
       [19, 13, 17, 17, 14, 15, 14],
       [12, 12, 17, 14, 10, 12, 14],
       [11, 12, 15, 17, 11, 13, 17],
       [18, 12, 19, 16, 13, 11, 12]])

In [67]:
np.split(x,[2,4])

[array([[12, 10, 12, 17, 15, 10, 10],
        [15, 15, 14, 17, 18, 11, 18]]),
 array([[19, 13, 17, 17, 14, 15, 14],
        [12, 12, 17, 14, 10, 12, 14]]),
 array([[11, 12, 15, 17, 11, 13, 17],
        [18, 12, 19, 16, 13, 11, 12]])]

In [69]:
np.hsplit(x,[2,4])

[array([[12, 10],
        [15, 15],
        [19, 13],
        [12, 12],
        [11, 12],
        [18, 12]]),
 array([[12, 17],
        [14, 17],
        [17, 17],
        [17, 14],
        [15, 17],
        [19, 16]]),
 array([[15, 10, 10],
        [18, 11, 18],
        [14, 15, 14],
        [10, 12, 14],
        [11, 13, 17],
        [13, 11, 12]])]

In [71]:
np.vsplit(x,3)

[array([[12, 10, 12, 17, 15, 10, 10],
        [15, 15, 14, 17, 18, 11, 18]]),
 array([[19, 13, 17, 17, 14, 15, 14],
        [12, 12, 17, 14, 10, 12, 14]]),
 array([[11, 12, 15, 17, 11, 13, 17],
        [18, 12, 19, 16, 13, 11, 12]])]

In [73]:
x=np.random.randint(1,6,size=(3,4))
x


array([[2, 2, 5, 3],
       [2, 3, 1, 4],
       [5, 1, 1, 5]])

In [75]:
x.sum()

34

In [77]:
x.sum(axis=0)

array([ 9,  6,  7, 12])

In [79]:
x.sum(axis=1)

array([12, 10, 12])

In [81]:
x.mean()

2.8333333333333335

In [83]:
x.mean(axis=0)

array([3.        , 2.        , 2.33333333, 4.        ])

In [85]:
x.mean(axis=1)

array([3. , 2.5, 3. ])

In [87]:
from statistics import mode

In [89]:
y=np.array([10,20,30,40])
y

array([10, 20, 30, 40])

In [91]:
mode(y)

10

In [93]:
y=np.array([10,20,30,40,20])
y

array([10, 20, 30, 40, 20])

In [95]:
mode(y)

20

In [97]:
y=np.array([10,20,30,40,20,10])
y

array([10, 20, 30, 40, 20, 10])

In [99]:
mode(y)

10

In [101]:
y=np.array([10,20,30,40,50,60])
y

array([10, 20, 30, 40, 50, 60])

In [103]:
np.median(y)

35.0

In [105]:
y=np.array([10,20,30,40,50,60,70])
y

array([10, 20, 30, 40, 50, 60, 70])

In [107]:
np.median(y)

40.0

In [109]:
y=np.array([10,20,30,40,50,60,5000])
y

array([  10,   20,   30,   40,   50,   60, 5000])

In [111]:
np.mean(y)

744.2857142857143

In [113]:
np.median(y)

40.0

In [115]:
y=np.array([10,20,30,40,50,60])
y

array([10, 20, 30, 40, 50, 60])

In [117]:
.20*6

1.2000000000000002

In [119]:
#i+g=   q*(n-1)+1

In [121]:
#20th percentile

In [123]:
n=6
20/100*(n-1)+1


2.0

In [125]:
np.percentile(y,20)

20.0

In [127]:
#30th percentile

In [129]:
h=30/100*(n-1)+1
h

2.5

In [131]:
i=2
g=.5

In [133]:
perc=20+g*(30-20)
perc

25.0

In [135]:
np.percentile(y,30)

25.0

In [137]:
x

array([[2, 2, 5, 3],
       [2, 3, 1, 4],
       [5, 1, 1, 5]])

In [139]:
x.max()

5

In [141]:
x.min()

1

In [143]:
x.max(axis=0)

array([5, 3, 5, 5])

In [145]:
x.max(axis=1)

array([5, 4, 5])

In [147]:
x.min()

1

In [149]:
x.min(axis=0)

array([2, 1, 1, 3])

In [151]:
x

array([[2, 2, 5, 3],
       [2, 3, 1, 4],
       [5, 1, 1, 5]])

In [153]:
x.min(axis=1)

array([2, 1, 1])