## PRANABESH SENGUPTA MCA-DIATM

## chatbot application

In [1]:
import numpy as np
import pandas as pd

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
import json

In [4]:
with open('intents.json') as f:
    r=json.load(f)

r

{'intents': [{'tag': 'greeting',
   'patterns': ['Hi there',
    'How are you? ',
    'Is anyone there?',
    'Hey',
    'Hola',
    'Hello',
    'Good day'],
   'responses': ['Hi there, how can I help?',
    'Welcome to our web portal',
    'Good Day']},
  {'tag': 'goodbye',
   'patterns': ['Bye',
    'See you later',
    'Goodbye',
    'Nice chatting to you, bye',
    'Till next time'],
   'responses': ['See you!', 'Have a nice day', 'Bye! Come back again soon.']},
  {'tag': 'thanks',
   'patterns': ['Thanks',
    'Thank you',
    "That's helpful",
    'Awesome, thanks',
    'Thanks for helping me'],
   'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
  {'tag': 'noanswer',
   'patterns': [],
   'responses': ["Sorry, can't understand you",
    'Please give me more info',
    'Not sure I understand']},
  {'tag': 'options',
   'patterns': ['How you could help me?',
    'What you can do?',
    'What help you provide?',
    'How you can be helpful?',
    'What support is offe

In [5]:
doc=r['intents']
doc

[{'tag': 'greeting',
  'patterns': ['Hi there',
   'How are you? ',
   'Is anyone there?',
   'Hey',
   'Hola',
   'Hello',
   'Good day'],
  'responses': ['Hi there, how can I help?',
   'Welcome to our web portal',
   'Good Day']},
 {'tag': 'goodbye',
  'patterns': ['Bye',
   'See you later',
   'Goodbye',
   'Nice chatting to you, bye',
   'Till next time'],
  'responses': ['See you!', 'Have a nice day', 'Bye! Come back again soon.']},
 {'tag': 'thanks',
  'patterns': ['Thanks',
   'Thank you',
   "That's helpful",
   'Awesome, thanks',
   'Thanks for helping me'],
  'responses': ['Happy to help!', 'Any time!', 'My pleasure']},
 {'tag': 'noanswer',
  'patterns': [],
  'responses': ["Sorry, can't understand you",
   'Please give me more info',
   'Not sure I understand']},
 {'tag': 'options',
  'patterns': ['How you could help me?',
   'What you can do?',
   'What help you provide?',
   'How you can be helpful?',
   'What support is offered'],
  'responses': ['I can guide you through

In [6]:
classes=[]
patterns=[]
for i in doc:
    if i['patterns']:
        ##it takes the pattern
        print(i)
        classes.append(i['tag'])
        patterns.extend(i['patterns'])
        print('====')

{'tag': 'greeting', 'patterns': ['Hi there', 'How are you? ', 'Is anyone there?', 'Hey', 'Hola', 'Hello', 'Good day'], 'responses': ['Hi there, how can I help?', 'Welcome to our web portal', 'Good Day']}
====
{'tag': 'goodbye', 'patterns': ['Bye', 'See you later', 'Goodbye', 'Nice chatting to you, bye', 'Till next time'], 'responses': ['See you!', 'Have a nice day', 'Bye! Come back again soon.']}
====
{'tag': 'thanks', 'patterns': ['Thanks', 'Thank you', "That's helpful", 'Awesome, thanks', 'Thanks for helping me'], 'responses': ['Happy to help!', 'Any time!', 'My pleasure']}
====
{'tag': 'options', 'patterns': ['How you could help me?', 'What you can do?', 'What help you provide?', 'How you can be helpful?', 'What support is offered'], 'responses': ['I can guide you through Adverse drug reaction list, Blood pressure tracking, Hospitals and Pharmacies', 'Offering support for Adverse drug reaction, Blood pressure, Hospitals and Pharmacies'], 'context': ['']}
====
{'tag': 'adverse_drug',

In [7]:
classes

['greeting',
 'goodbye',
 'thanks',
 'options',
 'adverse_drug',
 'blood_pressure',
 'blood_pressure_search',
 'pharmacy_search',
 'hospital_search']

In [8]:
len(classes)

9

In [9]:
patterns

['Hi there',
 'How are you? ',
 'Is anyone there?',
 'Hey',
 'Hola',
 'Hello',
 'Good day',
 'Bye',
 'See you later',
 'Goodbye',
 'Nice chatting to you, bye',
 'Till next time',
 'Thanks',
 'Thank you',
 "That's helpful",
 'Awesome, thanks',
 'Thanks for helping me',
 'How you could help me?',
 'What you can do?',
 'What help you provide?',
 'How you can be helpful?',
 'What support is offered',
 'How to check Adverse drug reaction?',
 'Open adverse drugs module',
 'Give me a list of drugs causing adverse behavior',
 'List all drugs suitable for patient with adverse reaction',
 'Which drugs dont have adverse reaction?',
 'Open blood pressure module',
 'Task related to blood pressure',
 'Blood pressure data entry',
 'I want to log blood pressure results',
 'Blood pressure data management',
 'cricket score',
 'I want to search for blood pressure result history',
 'Blood pressure for patient',
 'Load patient blood pressure result',
 'Show blood pressure results for patient',
 'Find blood

In [23]:
#vocabulary

In [12]:
cv=CountVectorizer(stop_words='english')

In [13]:
cv

CountVectorizer(stop_words='english')

In [14]:
cv.fit_transform(patterns)

<49x64 sparse matrix of type '<class 'numpy.int64'>'
	with 122 stored elements in Compressed Sparse Row format>

In [15]:
d=cv.fit_transform(patterns).toarray()
d

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
cv.get_feature_names_out()

array(['adverse', 'awesome', 'behavior', 'blood', 'bye', 'causing',
       'chatting', 'check', 'cricket', 'data', 'day', 'details', 'dont',
       'drug', 'drugs', 'entry', 'good', 'goodbye', 'hello', 'help',
       'helpful', 'helping', 'hey', 'hi', 'history', 'hola', 'hospital',
       'id', 'later', 'list', 'load', 'locate', 'log', 'looking',
       'lookup', 'management', 'module', 'movie', 'nearby', 'nice',
       'offered', 'open', 'patient', 'pharmacies', 'pharmacy', 'pressure',
       'provide', 'reaction', 'related', 'result', 'results', 'review',
       'score', 'search', 'searching', 'suitable', 'support', 'task',
       'thank', 'thanks', 'till', 'time', 'transfer', 'want'],
      dtype=object)

In [17]:
df=pd.DataFrame(d,columns=cv.get_feature_names_out())
df

adverse  awesome  behavior  blood  bye  causing  chatting  check  cricket  \
0         0        0         0      0    0        0         0      0        0   
1         0        0         0      0    0        0         0      0        0   
2         0        0         0      0    0        0         0      0        0   
3         0        0         0      0    0        0         0      0        0   
4         0        0         0      0    0        0         0      0        0   
5         0        0         0      0    0        0         0      0        0   
6         0        0         0      0    0        0         0      0        0   
7         0        0         0      0    1        0         0      0        0   
8         0        0         0      0    0        0         0      0        0   
9         0        0         0      0    0        0         0      0        0   
10        0        0         0      0    1        0         1      0        0   
11        0        0         0      0    0        0         0      0        0   
12        0        0         0      0    0        0         0      0        0   
13        0        0         0      0    0        0         0      0        0   
14        0        0         0      0    0        0         0      0        0   
15        0        1         0      0    0        0         0      0        0   
16        0        0         0      0    0        0         0      0        0   
17        0        0         0      0    0        0         0      0        0   
18        0        0         0      0    0        0         0      0        0   
19        0        0         0      0    0        0         0      0        0   
20        0        0         0      0    0        0         0      0        0   
21        0        0         0      0    0        0         0      0        0   
22        1        0         0      0    0        0         0      1        0   
23        1        0         0      0    0        0         0      0        0   
24        1        0         1      0    0        1         0      0        0   
25        1        0         0      0    0        0         0      0        0   
26        1        0         0      0    0        0         0      0        0   
27        0        0         0      1    0        0         0      0        0   
28        0        0         0      1    0        0         0      0        0   
29        0        0         0      1    0        0         0      0        0   
30        0        0         0      1    0        0         0      0        0   
31        0        0         0      1    0        0         0      0        0   
32        0        0         0      0    0        0         0      0        1   
33        0        0         0      1    0        0         0      0        0   
34        0        0         0      1    0        0         0      0        0   
35        0        0         0      1    0        0         0      0        0   
36        0        0         0      1    0        0         0      0        0   
37        0        0         0      1    0        0         0      0        0   
38        0        0         0      0    0        0         0      0        0   
39        0        0         0      0    0        0         0      0        0   
40        0        0         0      0    0        0         0      0        0   
41        0        0         0      0    0        0         0      0        0   
42        0        0         0      0    0        0         0      0        0   
43        0        0         0      0    0        0         0      0        0   
44        0        0         0      0    0        0         0      0        0   
45        0        0         0      0    0        0         0      0        0   
46        0        0         0      0    0        0         0      0        0   
47        0        0         0      0    0        0         0      0        0   
48        0        0         0     

In [18]:
y=[]
for i in patterns:
    for j in doc:
        if i in j['patterns']:
            y.append(j['tag'])
y

['greeting',
 'greeting',
 'greeting',
 'greeting',
 'greeting',
 'greeting',
 'greeting',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'goodbye',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'options',
 'options',
 'options',
 'options',
 'options',
 'adverse_drug',
 'adverse_drug',
 'adverse_drug',
 'adverse_drug',
 'adverse_drug',
 'blood_pressure',
 'blood_pressure',
 'blood_pressure',
 'blood_pressure',
 'blood_pressure',
 'blood_pressure',
 'blood_pressure_search',
 'blood_pressure_search',
 'blood_pressure_search',
 'blood_pressure_search',
 'blood_pressure_search',
 'pharmacy_search',
 'pharmacy_search',
 'pharmacy_search',
 'pharmacy_search',
 'pharmacy_search',
 'hospital_search',
 'hospital_search',
 'hospital_search',
 'hospital_search',
 'hospital_search',
 'hospital_search']

In [19]:
len(y)

49

## model creation

In [20]:
from keras.models import Sequential

In [21]:
from keras.layers import Dense,Dropout

In [22]:
X=df

In [23]:
X.shape

(49, 64)

In [24]:
model = Sequential([Dense(100,activation='relu',input_dim=X.shape[1]),Dense(9,activation='Softmax')])

In [31]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
en=LabelEncoder()
y_encoded=en.fit_transform(y)
y_encoded

array([4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 5,
       5, 5, 5, 5, 5], dtype=int64)

In [32]:
model.fit(X,y_encoded,epochs=100,validation_split=.2)

Epoch 1/100
2/2 [==============================] - 3s 589ms/step - loss: 2.2196 - accuracy: 0.0513 - val_loss: 2.1059 - val_accuracy: 0.2000
Epoch 2/100
2/2 [==============================] - 0s 25ms/step - loss: 2.1872 - accuracy: 0.0769 - val_loss: 2.1161 - val_accuracy: 0.1000
Epoch 3/100
2/2 [==============================] - 0s 21ms/step - loss: 2.1606 - accuracy: 0.1795 - val_loss: 2.1272 - val_accuracy: 0.1000
Epoch 4/100
2/2 [==============================] - 0s 20ms/step - loss: 2.1323 - accuracy: 0.3333 - val_loss: 2.1388 - val_accuracy: 0.1000
Epoch 5/100
2/2 [==============================] - 0s 32ms/step - loss: 2.1068 - accuracy: 0.3333 - val_loss: 2.1507 - val_accuracy: 0.0000e+00
Epoch 6/100
2/2 [==============================] - 0s 31ms/step - loss: 2.0821 - accuracy: 0.4103 - val_loss: 2.1620 - val_accuracy: 0.0000e+00
Epoch 7/100
2/2 [==============================] - 0s 30ms/step - loss: 2.0575 - accuracy: 0.4103 - val_loss: 2.1724 - val_accuracy: 0.0000e+00
Epoch 8

Epoch 59/100
2/2 [==============================] - 0s 24ms/step - loss: 0.9575 - accuracy: 0.9487 - val_loss: 2.6782 - val_accuracy: 0.1000
Epoch 60/100
2/2 [==============================] - 0s 51ms/step - loss: 0.9407 - accuracy: 0.9487 - val_loss: 2.6860 - val_accuracy: 0.1000
Epoch 61/100
2/2 [==============================] - 0s 30ms/step - loss: 0.9244 - accuracy: 0.9487 - val_loss: 2.6928 - val_accuracy: 0.1000
Epoch 62/100
2/2 [==============================] - 0s 47ms/step - loss: 0.9083 - accuracy: 0.9487 - val_loss: 2.7003 - val_accuracy: 0.1000
Epoch 63/100
2/2 [==============================] - 0s 30ms/step - loss: 0.8921 - accuracy: 0.9487 - val_loss: 2.7088 - val_accuracy: 0.1000
Epoch 64/100
2/2 [==============================] - 0s 39ms/step - loss: 0.8763 - accuracy: 0.9487 - val_loss: 2.7180 - val_accuracy: 0.1000
Epoch 65/100
2/2 [==============================] - 0s 41ms/step - loss: 0.8607 - accuracy: 0.9487 - val_loss: 2.7266 - val_accuracy: 0.1000
Epoch 66/100


In [33]:
s='Thank you'

In [35]:
X_test=cv.transform([s]).toarray()
X_test

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]],
      dtype=int64)

In [37]:
prob=model.predict(X_test)
prob

1/1 [==============================] - 0s 16ms/step


array([[0.06183182, 0.05088063, 0.02505514, 0.08593997, 0.17333712,
        0.02528961, 0.13488594, 0.03921001, 0.4035697 ]], dtype=float32)

In [38]:
index=np.argmax(prob)
index

8

In [39]:
classes

['greeting',
 'goodbye',
 'thanks',
 'options',
 'adverse_drug',
 'blood_pressure',
 'blood_pressure_search',
 'pharmacy_search',
 'hospital_search']

In [40]:
sorted(classes)[index]

'thanks'