#pandas-->python library for data analysis(1.Series 2.Data Frame)

#creating series----->
#1.using list
#2.using array
#3.using linspace
#4.using dictonary
#5.using scaler value

In [23]:
import pandas as pd
import numpy as np

In [11]:
x=pd.Series([10,20,30])
x

0    10
1    20
2    30
dtype: int64

In [17]:
pd.Series(10,index=range(10,19))
          

10    10
11    10
12    10
13    10
14    10
15    10
16    10
17    10
18    10
dtype: int64

In [21]:
pd.Series(10,index=list('abcdef'))        

a    10
b    10
c    10
d    10
e    10
f    10
dtype: int64

In [25]:
pd.Series(np.linspace(10,20,5))
          

0    10.0
1    12.5
2    15.0
3    17.5
4    20.0
dtype: float64

In [27]:
d={'tv':5000,'printer':6000,'monitor':8000}
d

{'tv': 5000, 'printer': 6000, 'monitor': 8000}

In [29]:
pd.Series(d)          

tv         5000
printer    6000
monitor    8000
dtype: int64

In [35]:
pd.Series(d,index=list('abc'))     #index don't match   

a   NaN
b   NaN
c   NaN
dtype: float64

In [45]:
s=pd.Series(range(10,20))  
s

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

properties of pandas

In [47]:
s.shape

(10,)

In [49]:
s.nbytes

80

In [51]:
s.index

RangeIndex(start=0, stop=10, step=1)

In [53]:
s.values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64)

In [55]:
s.values.reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]], dtype=int64)

In [57]:
s.hasnans

False

In [59]:
s.empty

False

In [61]:
s.ndim

1

#series operation

In [67]:
s

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [69]:
s[9]

19

##slicing

In [72]:
s[:4]

0    10
1    11
2    12
3    13
dtype: int64

In [74]:
s[4:]

4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [76]:
s[5:1:-1]

5    15
4    14
3    13
2    12
dtype: int64

In [87]:
s=pd.Series(range(10,20),index=list('abcdeaklcd')) 
s

a    10
b    11
c    12
d    13
e    14
a    15
k    16
l    17
c    18
d    19
dtype: int64

In [91]:
s['a':'d']

KeyError: "Cannot get left slice bound for non-unique label: 'a'"

In [99]:
s.sort_index(inplace=True)

In [101]:
s

a    10
a    15
b    11
c    12
c    18
d    13
d    19
e    14
k    16
l    17
dtype: int64

In [103]:
s['a':'d']

a    10
a    15
b    11
c    12
c    18
d    13
d    19
dtype: int64

In [107]:
s.sort_values(ascending=False)

d    19
c    18
l    17
k    16
a    15
e    14
d    13
c    12
b    11
a    10
dtype: int64

In [125]:
s[s>13] #masking(bool)

a    15
c    18
d    19
e    14
k    16
l    17
dtype: int64

In [131]:
m=(s>12) & (s<16)
m

a    False
a     True
b    False
c    False
c    False
d     True
d    False
e     True
k    False
l    False
dtype: bool

In [133]:
s[m]

a    15
d    13
e    14
dtype: int64

In [135]:
s1=pd.Series(range(1,5))
s2=pd.Series(range(11,17))
s1,s2

(0    1
 1    2
 2    3
 3    4
 dtype: int64,
 0    11
 1    12
 2    13
 3    14
 4    15
 5    16
 dtype: int64)

In [137]:
a=np.array([1,2,3,4])
b=np.array([1,2])
a,b

(array([1, 2, 3, 4]), array([1, 2]))

In [139]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [141]:
s1+s2

0    12.0
1    14.0
2    16.0
3    18.0
4     NaN
5     NaN
dtype: float64