In [1]:
#Boolean Indexing

In [3]:
import numpy as np

In [7]:
x=np.random.randint(10,20,size=10)
x

array([12, 17, 14, 19, 19, 12, 13, 10, 10, 15])

In [9]:
#boolean mask=>"array of boolean value"

In [11]:
a=[True,False,True,False,True,False,False,True,True,True]

In [13]:
x[a]

array([12, 14, 19, 10, 10, 15])

In [15]:
b=np.random.randint(0,2,size=10)
b

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 0])

In [17]:
#astype()=>"it is used to change the data type"[instance method]
#1.astype(int/flot/bool)

In [21]:
mask=b.astype(bool)
mask

array([ True, False,  True, False, False,  True, False,  True,  True,
       False])

In [23]:
x[mask]

array([12, 14, 12, 10, 10])

In [25]:
x[x>14]

array([17, 19, 19, 15])

In [31]:
#multiple condition

In [33]:
#and &(bitwise operator)
#or |
#not ~

In [35]:
x

array([12, 17, 14, 19, 19, 12, 13, 10, 10, 15])

In [43]:
c=(x>14) | (x<19)
c

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [45]:
#boolean Indexing for 2d array

In [47]:
y=np.random.randint(10,20,size=(6,5))
y

array([[16, 10, 18, 13, 17],
       [13, 19, 14, 13, 11],
       [10, 12, 12, 19, 13],
       [19, 10, 13, 18, 19],
       [14, 17, 15, 17, 18],
       [12, 13, 16, 17, 14]])

In [49]:
y>15

array([[ True, False,  True, False,  True],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [ True, False, False,  True,  True],
       [False,  True, False,  True,  True],
       [False, False,  True,  True, False]])

In [55]:
y[y>15]

array([16, 18, 17, 19, 19, 19, 18, 19, 17, 17, 18, 16, 17])

In [57]:
y[2]>15

array([False, False, False,  True, False])

In [59]:
#fancy indexing
#x[ [row] , [col] ]

In [61]:
y

array([[16, 10, 18, 13, 17],
       [13, 19, 14, 13, 11],
       [10, 12, 12, 19, 13],
       [19, 10, 13, 18, 19],
       [14, 17, 15, 17, 18],
       [12, 13, 16, 17, 14]])

In [63]:
y.shape

(6, 5)

In [65]:
r=np.random.randint(0,2,size=6).astype(bool)
r

array([False,  True, False, False, False,  True])

In [89]:
c=np.random.randint(0,2,size=5).astype(bool) # col!=row so can't use y[r,c]
c

array([ True,  True, False,  True,  True])

In [79]:
z=y[r]
z

array([[13, 19, 14, 13, 11],
       [12, 13, 16, 17, 14]])

In [85]:
z[:,c]

array([[19, 13, 11],
       [13, 17, 14]])

In [87]:
y[r][:,c]

array([[19, 13, 11],
       [13, 17, 14]])

In [91]:
y

array([[16, 10, 18, 13, 17],
       [13, 19, 14, 13, 11],
       [10, 12, 12, 19, 13],
       [19, 10, 13, 18, 19],
       [14, 17, 15, 17, 18],
       [12, 13, 16, 17, 14]])

In [97]:
y[y>15]=1000
y

array([[1000,   10, 1000,   13, 1000],
       [  13, 1000,   14,   13,   11],
       [  10,   12,   12, 1000,   13],
       [1000,   10,   13, 1000, 1000],
       [  14, 1000,   15, 1000, 1000],
       [  12,   13, 1000, 1000,   14]])

In [101]:
y[(y>12) &(y<18)]=5000
y

array([[1000,   10, 1000, 5000, 1000],
       [5000, 1000, 5000, 5000,   11],
       [  10,   12,   12, 1000, 5000],
       [1000,   10, 5000, 1000, 1000],
       [5000, 1000, 5000, 1000, 1000],
       [  12, 5000, 1000, 1000, 5000]])

In [103]:
#2nd way

In [107]:
t=np.where(y>40)
t

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5,
        5], dtype=int64),
 array([0, 2, 3, 4, 0, 1, 2, 3, 3, 4, 0, 2, 3, 4, 0, 1, 2, 3, 4, 1, 2, 3,
        4], dtype=int64))

In [109]:
np.where(y>40,5000,4000)

array([[5000, 4000, 5000, 5000, 5000],
       [5000, 5000, 5000, 5000, 4000],
       [4000, 4000, 4000, 5000, 5000],
       [5000, 4000, 5000, 5000, 5000],
       [5000, 5000, 5000, 5000, 5000],
       [4000, 5000, 5000, 5000, 5000]])

In [111]:
np.where(y>40,5000,y)

array([[5000,   10, 5000, 5000, 5000],
       [5000, 5000, 5000, 5000,   11],
       [  10,   12,   12, 5000, 5000],
       [5000,   10, 5000, 5000, 5000],
       [5000, 5000, 5000, 5000, 5000],
       [  12, 5000, 5000, 5000, 5000]])

In [115]:
x=np.array([2,5,6])
x

array([2, 5, 6])

In [117]:
x.astype(float)

array([2., 5., 6.])

In [119]:
x.astype('O')

array([2, 5, 6], dtype=object)

In [125]:
z=np.random.randint(10,20,size=(4,5))
z

array([[15, 18, 14, 10, 19],
       [10, 13, 18, 13, 16],
       [13, 16, 13, 19, 10],
       [13, 15, 10, 13, 18]])

In [127]:
z.shape

(4, 5)

In [129]:
z.reshape(10,2)

array([[15, 18],
       [14, 10],
       [19, 10],
       [13, 18],
       [13, 16],
       [13, 16],
       [13, 19],
       [10, 13],
       [15, 10],
       [13, 18]])

In [131]:
z.reshape(2,2,5)

array([[[15, 18, 14, 10, 19],
        [10, 13, 18, 13, 16]],

       [[13, 16, 13, 19, 10],
        [13, 15, 10, 13, 18]]])

In [133]:
m=np.random.randint(10,20,size=10)
m

array([14, 10, 11, 19, 16, 11, 17, 17, 14, 15])

In [137]:
m.reshape(2,-1) #unkonwn (-1)

array([[14, 10, 11, 19, 16],
       [11, 17, 17, 14, 15]])