In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [100]:
df=pd.read_csv('cars.csv')
df.head()

Car_ID    Brand    Model  Year  Kilometers_Driven Fuel_Type Transmission  \
0       1   Toyota  Corolla  2018              50000    Petrol       Manual   
1       2    Honda    Civic  2019              40000    Petrol    Automatic   
2       3     Ford  Mustang  2017              20000    Petrol    Automatic   
3       4   Maruti    Swift  2020              30000    Diesel       Manual   
4       5  Hyundai   Sonata  2016              60000    Diesel    Automatic   

  Owner_Type  Mileage  Engine  Power  Seats    Price  
0      First       15    1498    108      5   800000  
1     Second       17    1597    140      5  1000000  
2      First       10    4951    395      4  2500000  
3      Third       23    1248     74      5   600000  
4     Second       18    1999    194      5   850000

In [102]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder

In [104]:
x=np.array(['mango','banana','apple'])
lb=LabelEncoder()
ord=OrdinalEncoder()
ohe=OneHotEncoder(sparse_output=False)

In [33]:
lb.fit_transform(x) #1d array passing...

array([2, 1, 0], dtype=int64)

In [35]:
ord.fit_transform(x.reshape(-1,1)) #2d array passing...

array([[2.],
       [1.],
       [0.]])

In [47]:
ohe.fit_transform(x.reshape(-1,1)) #arrange item in alphabetic

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [106]:
df.drop(columns='Car_ID',inplace=True)

In [108]:
df

Brand          Model  Year  Kilometers_Driven Fuel_Type Transmission  \
0     Toyota        Corolla  2018              50000    Petrol       Manual   
1      Honda          Civic  2019              40000    Petrol    Automatic   
2       Ford        Mustang  2017              20000    Petrol    Automatic   
3     Maruti          Swift  2020              30000    Diesel       Manual   
4    Hyundai         Sonata  2016              60000    Diesel    Automatic   
..       ...            ...   ...                ...       ...          ...   
95  Mercedes        C-Class  2019              22000    Diesel    Automatic   
96    Toyota  Innova Crysta  2017              38000    Diesel       Manual   
97      Ford       EcoSport  2018              26000    Petrol       Manual   
98   Hyundai          Verna  2019              24000    Petrol    Automatic   
99      Tata         Altroz  2020              18000    Petrol       Manual   

   Owner_Type  Mileage  Engine  Power  Seats    Price  
0       First       15    1498    108      5   800000  
1      Second       17    1597    140      5  1000000  
2       First       10    4951    395      4  2500000  
3       Third       23    1248     74      5   600000  
4      Second       18    1999    194      5   850000  
..        ...      ...     ...    ...    ...      ...  
95      First       16    1950    191      5  2900000  
96     Second       13    2755    171      7  1400000  
97      Third       18    1497    121      5   750000  
98     Second       17    1497    113      5   850000  
99      First       20    1199     85      5   600000  

[100 rows x 12 columns]

In [110]:
c=df.select_dtypes('O').columns
c

Index(['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Owner_Type'], dtype='object')

Index(['Brand', 'Model', 'Fuel_Type', 'Transmission', 'Owner_Type'], dtype='object')

In [112]:
for i in c:
    df[i]=lb.fit_transform(df[i])
df

Brand  Model  Year  Kilometers_Driven  Fuel_Type  Transmission  \
0       9     15  2018              50000          1             1   
1       3     14  2019              40000          1             0   
2       2     30  2017              20000          1             0   
3       6     42  2020              30000          0             1   
4       4     41  2016              60000          0             0   
..    ...    ...   ...                ...        ...           ...   
95      7     11  2019              22000          0             0   
96      9     29  2017              38000          0             1   
97      2     18  2018              26000          1             1   
98      4     50  2019              24000          1             0   
99      8      7  2020              18000          1             1   

    Owner_Type  Mileage  Engine  Power  Seats    Price  
0            0       15    1498    108      5   800000  
1            1       17    1597    140      5  1000000  
2            0       10    4951    395      4  2500000  
3            2       23    1248     74      5   600000  
4            1       18    1999    194      5   850000  
..         ...      ...     ...    ...    ...      ...  
95           0       16    1950    191      5  2900000  
96           1       13    2755    171      7  1400000  
97           2       18    1497    121      5   750000  
98           1       17    1497    113      5   850000  
99           0       20    1199     85      5   600000  

[100 rows x 12 columns]

In [59]:
df.Transmission.value_counts()

Transmission
Automatic    57
Manual       43
Name: count, dtype: int64

In [67]:
df.select_dtypes(['int64']).corr()

Brand  Model      Year  Kilometers_Driven  Fuel_Type  \
Brand                NaN    NaN       NaN                NaN        NaN   
Model                NaN    NaN       NaN                NaN        NaN   
Year                 NaN    NaN  1.000000          -0.741176        NaN   
Kilometers_Driven    NaN    NaN -0.741176           1.000000        NaN   
Fuel_Type            NaN    NaN       NaN                NaN        NaN   
Transmission         NaN    NaN       NaN                NaN        NaN   
Owner_Type           NaN    NaN       NaN                NaN        NaN   
Mileage              NaN    NaN  0.213177          -0.104437        NaN   
Engine               NaN    NaN -0.355122           0.112340        NaN   
Power                NaN    NaN -0.249446          -0.026732        NaN   
Seats                NaN    NaN -0.252598           0.396443        NaN   
Price                NaN    NaN -0.232687          -0.051104        NaN   

                   Transmission  Owner_Type   Mileage    Engine     Power  \
Brand                       NaN         NaN       NaN       NaN       NaN   
Model                       NaN         NaN       NaN       NaN       NaN   
Year                        NaN         NaN  0.213177 -0.355122 -0.249446   
Kilometers_Driven           NaN         NaN -0.104437  0.112340 -0.026732   
Fuel_Type                   NaN         NaN       NaN       NaN       NaN   
Transmission                NaN         NaN       NaN       NaN       NaN   
Owner_Type                  NaN         NaN       NaN       NaN       NaN   
Mileage                     NaN         NaN  1.000000 -0.680949 -0.648894   
Engine                      NaN         NaN -0.680949  1.000000  0.805709   
Power                       NaN         NaN -0.648894  0.805709  1.000000   
Seats                       NaN         NaN -0.194581  0.179179 -0.102867   
Price                       NaN         NaN -0.595252  0.714465  0.856620   

                      Seats     Price  
Brand                   NaN       NaN  
Model                   NaN       NaN  
Year              -0.252598 -0.232687  
Kilometers_Driven  0.396443 -0.051104  
Fuel_Type               NaN       NaN  
Transmission            NaN       NaN  
Owner_Type              NaN       NaN  
Mileage           -0.194581 -0.595252  
Engine             0.179179  0.714465  
Power             -0.102867  0.856620  
Seats              1.000000 -0.000027  
Price             -0.000027  1.000000

In [75]:
df1=pd.read_csv('Social_Network_Ads.csv')

In [77]:
df1

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [81]:
df1.drop(columns='User ID',inplace=True)

In [83]:
df1

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]