In [1]:
import numpy as np

In [3]:
y=[12,24,30,45]

In [5]:
y[1:3]={'tv':5000,'monitor':6000}

In [7]:
y

[12, 'tv', 'monitor', 45]

In [9]:
#numpy broadcasting

In [11]:
#2d array

In [13]:
x=np.random.randint(10,20,size=(6,5))

In [15]:
x

array([[16, 11, 19, 17, 15],
       [12, 15, 14, 16, 19],
       [11, 16, 15, 18, 15],
       [15, 10, 15, 16, 19],
       [18, 16, 15, 11, 19],
       [11, 16, 16, 16, 17]])

In [17]:
x[2]

array([11, 16, 15, 18, 15])

In [19]:
x[2,3]

18

In [21]:
x[:3]

array([[16, 11, 19, 17, 15],
       [12, 15, 14, 16, 19],
       [11, 16, 15, 18, 15]])

In [23]:
x[2:4,:3]

array([[11, 16, 15],
       [15, 10, 15]])

In [25]:
x[:,:3]

array([[16, 11, 19],
       [12, 15, 14],
       [11, 16, 15],
       [15, 10, 15],
       [18, 16, 15],
       [11, 16, 16]])

In [27]:
x[2:4,:]

array([[11, 16, 15, 18, 15],
       [15, 10, 15, 16, 19]])

In [29]:
x

array([[16, 11, 19, 17, 15],
       [12, 15, 14, 16, 19],
       [11, 16, 15, 18, 15],
       [15, 10, 15, 16, 19],
       [18, 16, 15, 11, 19],
       [11, 16, 16, 16, 17]])

In [31]:
x[0]=10000

In [33]:
x

array([[10000, 10000, 10000, 10000, 10000],
       [   12,    15,    14,    16,    19],
       [   11,    16,    15,    18,    15],
       [   15,    10,    15,    16,    19],
       [   18,    16,    15,    11,    19],
       [   11,    16,    16,    16,    17]])