In [1]:
import numpy as np

In [3]:
x=np.random.randint(10,20,size=(4,5))
x

array([[19, 14, 13, 18, 19],
       [10, 17, 10, 12, 12],
       [14, 10, 11, 16, 11],
       [14, 13, 17, 19, 10]])

In [5]:
np.sort(x)

array([[13, 14, 18, 19, 19],
       [10, 10, 12, 12, 17],
       [10, 11, 11, 14, 16],
       [10, 13, 14, 17, 19]])

In [7]:
np.sort(x,axis=0)

array([[10, 10, 10, 12, 10],
       [14, 13, 11, 16, 11],
       [14, 14, 13, 18, 12],
       [19, 17, 17, 19, 19]])

In [11]:
#stacking--->merging array dim=>dim+1